### ISSUE TITLE
Error: module utl_dlinklist is in file 'pham/utl_dlinklist.d' which cannot be read

### ISSUE THREAD

**Issue by Robert-M-Muench** [apz28/D-xml#1]
There seems to be a hidden dependency:

/Users/robby/.dub/packages/xml-1.0.0/xml/source/xml_buffer.d(17,8): Error: module utl_dlinklist is in file 'pham/utl_dlinklist.d' which cannot be read

Just having xml as dub dependency gives this error.

**Comment by apz28** [comment]
Fixed
